// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1fUxrtsJLZ2KVCQFgmhmFUXLNd4JfHLk',
    appId: '1:900126030055:web:f5159687174f6c79f70a42',
    messagingSenderId: '900126030055',
    projectId: 'acm-ioit',
    authDomain: 'acm-ioit.firebaseapp.com',
    storageBucket: 'acm-ioit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9m6uKnxRP0RDjPgN6-pNE1UggDNVJ28',
    appId: '1:900126030055:android:c0451f127bda9876f70a42',
    messagingSenderId: '900126030055',
    projectId: 'acm-ioit',
    storageBucket: 'acm-ioit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLZ7R7FVAoyE_ZB3tsxGpIriymp_UrCw',
    appId: '1:900126030055:ios:a1aefaa69e54219ef70a42',
    messagingSenderId: '900126030055',
    projectId: 'acm-ioit',
    storageBucket: 'acm-ioit.appspot.com',
    iosBundleId: 'com.example.acmIoit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLZ7R7FVAoyE_ZB3tsxGpIriymp_UrCw',
    appId: '1:900126030055:ios:ee79c69fd07df80af70a42',
    messagingSenderId: '900126030055',
    projectId: 'acm-ioit',
    storageBucket: 'acm-ioit.appspot.com',
    iosBundleId: 'com.example.acmIoit.RunnerTests',
  );
}
